version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9

    commands:
      - echo "Installing dependencies"
      - python3 -m pip install -r requirements.txt
  build:
    commands:
      - echo "Building..."
      - python3 manage.py migrate
artifacts:
  files:
    - '**/*'